name: luci-app-clash

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v1
    - name: Download SDK
    - name: Clone & Compile ipk
      env: 
        REPO_URL: https://github.com/frainzy1477/luci-app-clash
        REPO_BRANCH: New-LuciMaster-Lean
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH clash
        
    - name: Configure
      env:
        CONFIG_FILE: 'config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE clash/.config
      
