name: Luci-app-clash CI
on:
  release:
    types: [push, published]
  
  push:
    branches: 
      - New-LuciMaster-Lean

      
jobs:
  build:
    runs-on: ubuntu-18.04
    
    env:
      URL: https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64.tar.xz
    
    steps:
    - name: Checkout - clone repository
      uses: actions/checkout@v1
    
    - name: Download and untar sdk
      run: |
        wget $URL
        tar xvJf openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64.tar.xz

    - name: Clone - openwrt plugin source
      run: |
        cd openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64
        git clone -b openwrt-18.06 https://github.com/frainzy1477/luci-app-clash.git package/luci-theme-rosy
    
    - name: Config - copy build config
      run: cp ./config openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64/.config

    - name: Download - openwrt build dependencies
      run: |
        cd openwrt-$VERSION
        make package/luci-app-clash/compile V=99


    - name: Release - push to release file
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: openwrt-${{ env.VERSION }}/bin/packages/x86_64/base/*
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}

    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: luci-app-clash
        path: openwrt-${{ env.VERSION }}/bin/packages/x86_64/base/*
